### ISSUE TITLE
time of periastron error

### ISSUE THREAD

**Issue by ApolloChoe** [3fon3fonov/exostriker#115]
Hi!

I am a graduate student and analyzing RV data with your package. It's very nice!

I couldn't find the time of periastron in exostriker.

Should I calculate the time of periastron from the longitude of periastron?

Thank you.

**Comment by 3fon3fonov** [comment]
Do you mean this:

![Screenshot at 2023-06-23 09-39-13](https://github.com/3fon3fonov/exostriker/assets/44244057/3ae15005-f9be-4140-b545-ae6f0510c450)

t_\omega is not a fitting parameter in the Exo-Striker. Instead, we use the mean anomaly MA_0 for a given epoch. The main reason is because the Exo-Striker can fit N-body model to RV data, which return the osculating orbital parameters for a given epoch, thus t_\omega is not an appropriate parameter.

But you can still calculate it and also derive posteriors if you like, with the following function included in the Exo-Striker

![Screenshot at 2023-06-23 09-48-55](https://github.com/3fon3fonov/exostriker/assets/44244057/a01c207e-70ab-4d99-8b8c-9421aac37534)

I hope this helps.

**Comment by ApolloChoe** [comment]
Thanks!

It helped me a lot!
