### ISSUE TITLE
sharp limits in phase plots

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#27]
I suggest the hard range 0:P_p in phase plots as default.

Note also the units on y-axis are in round brackets instead of squared.

**Comment by 3fon3fonov** [comment]
Units were fixed. 
About the hard range, I would leave it as it is. Do you want to export plot that has a hard range on the model? I can imagine that it might be difficult to do that by holding the right mouse button. 

You can try when you need to export try the following three options:
* right-click on the plot --> Xaxis --> Manual select 0: P_p
* or somewhat less convenient, right-click on the plot --> Mouse Mode --> 1, and then simply select the range you want to zoom by holding the left mouse button.
* finally:  right-click on the plot --> export --> Matplotlib Window --> do whatever you want with the Matplotlib GUI.

**Comment by mzechmeister** [comment]
Indeed these manual actions are less convenient (looking up the period, manually setting the period while it is already there in the table).
With "hard", I meant sharp. I.e. the plot should be initialised/resetted to the sharp limits.

Vise versa zooming a bit out zoom to give extra margin is easy.

**Comment by 3fon3fonov** [comment]
This must be fixed now.

**Comment by mzechmeister** [comment]
Works when loading a new phase plot. Ok.

I would also expect it, when clicking the resetting 'A'.

**Comment by 3fon3fonov** [comment]
This is more complicated than I thought since I might have to make a custom padding for each plot. The padding is global when you press 'A'. I definitely want some padding on the RV, transit, and other plots. Let's keep this issue open, till I find a permanent solution for the Phase plots (e.g. custom user settings controls so the user can control the Auto behavior of each plot). To reset the plot with sharp limits, for now, you can simply select the plot back from the comboBox menu (e.g. phase pl. 1, etc.).

**Comment by mzechmeister** [comment]
Works when loading a new phase plot. Ok.

I would also expect it, when clicking the resetting 'A'.
