### ISSUE TITLE
installation without root

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#5]
Installation requires many root rights.
Would it be be possible to do it without root?

**Comment by 3fon3fonov** [comment]
Hi Mathias, 

I guess you are talking about the OpenSuse bash installation script. The problem is that there I am using the 'zypper' installer and I could not find how to run it as an ordinary user.  If you know how to make 'zypper' 
to install under the user account without root rights I will be happy to implement that way. For example the MAC OS bash script uses "brew" which installs under the user account with no need of root rights, But really, the "bash" installers are meant only to check if you have a given package and try to help you install it.  

In case the installer tells you that you are missing a python package like: "numpy" "scipy" or "matplotlib"
 you can always try to install these separately as user via pip. For example, instead of:

sudo zypper install python-numpy (as it will run in the script)

you can try:

pip install numpy --user 

Then run the scrip again, untill you get "yes", everywhere. Then agree to compile the fortran routines 
and you are done. I read (somewhere) that it is still advisable to do a system install for some of the Python 
packages, rather than a pip install and that's why I am using "zypper".
 
On the other hand if you are missing "csh", "gfortran" or "c++" compilers I am not so sure 
how you can install these easily without root rights.


Also, keep in mind that this is one time process. Once all the dependencies are satisfied on the machine you are using, you can always install the tool without the need to repeat this process.  If you are git cloning, however, is always advisable to re run the script and recompile the fortran minimizers and the swift lib.

Trifon

**Comment by mzechmeister** [comment]
So I got it installed with:
```bash
python3 -m pip install --upgrade pip --user
pip3 install pyqt5 --user
pip3 install pathos --user
pip3 install dynesty --user
pip3 install batman --user
```
Then I had the same problem as in #10.
I worked around this by uncommenting
https://github.com/3fon3fonov/trifon/blob/57cd9afeaefa12c09cc3b758feccf7cba6a7e26e/lib/RV_mod/__init__.py#L1528

I'm not a fan of installing many libraries and many I probably won't use. I don't need batman.
I think, it would good to have a lite version and then to specify addons.
So minimum must be installed. And optional rest could catched with `try import except`.

**Comment by mzechmeister** [comment]
You should create a `setup.py`. Then it is more platform independent and `--user` could be specified by the user,

**Comment by 3fon3fonov** [comment]
I can try make an setup.py as well a pip installer. it is on my radar, but I want to have a more complete tool first.

about #10 

pip install batman --> wrong

pip install batman-package --> correct

Remove the old and install the new and the tool will work.

**Comment by 3fon3fonov** [comment]
This request goes here:

https://github.com/3fon3fonov/exostriker/issues/50
