### ISSUE TITLE
Silent Fail for long file names for data load function

### ISSUE THREAD

**Issue by christianmatthe** [3fon3fonov/exostriker#54]
Loading a data set with too many characters in its name (limit 64?) fails without an error message and permanently disables loading additional data.

**Comment by 3fon3fonov** [comment]
Hi @christianmatthe,

Thank you for this report.

I guess you are trying to load RV data, yes?

If yes, I dont think it should "silent". In your stdout/stderr widget you must get error like this:

> 
===== 2020.01.16 13:01:19 =====
Traceback (most recent call last):
  File "es_gui.py", line 2243, in showDialog_RV_input_file
    self.init_fit()
  File "es_gui.py", line 2483, in init_fit
    self.update_plots() 
  File "es_gui.py", line 2106, in update_plots
    self.update_RV_plots()
  File "es_gui.py", line 2008, in update_RV_plots
    error_list = self.add_jitter(fit.fit_results.rv_model.rv_err, fit.filelist.idset)
  File "es_gui.py", line 2494, in add_jitter
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
  File "es_gui.py", line 2494, in <listcomp>
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
IndexError: list index out of range
> 

which comes from the fact, that the file was not loaded and thus the plots cannot be made.

Exo-Striker uses a Fortran77 routine for the modeling and 
(one of) the input parameter(s) is the absolute path of the file(s) you are loading. 
I.e. the files are loaded/read in Fortran, not in Python. This is a problem since Fortan77 
has 72 character limit per line (characters after column 72 are ignored).

I had this problem with very long absolute paths, and the solution was to make the Exo-Striker
copy your loaded file in /tmp and then remove it from there once you close the program.

For example; file that is in:

> 
/home/christianmatthe/Example/example2/example3/example4/HARPS_data_for_target_HDXXX.dat
> 

will not work, but 

> 
/tmp/xxx/HARPS_data_for_target_HDXXX.dat
> 

will work.


Now... if the file you are loading is with a super long name, I am afraid that we are back to the 72 character problem....

Unfortunately, this is not an easy fix at the moment. This will be resolved once I translate the Fortran code to a python library (it is planned to be done via f2py, but I need to overcome some other problems first). 



I promise to get back to this problem as soon as possible. Meanwhile, please truncate the 
filenames of your files :) 

 
But again, please confirm that you are loading RV data.
